### ISSUE TITLE
ListenerChain does not support org.testng.IExecutionListener type of listeners

### ISSUE THREAD

**Issue by psamovich** [Nordstrom/TestNG-Foundation#27]
It would be nice to add support for IExecutionListener type

**Comment by sbabcoc** [comment]
It's been a long time since I looked at this, but I think the reason I chose not to support **`IExecutionListener`** in **`ListenerChain`** is that the notifications published for this interface fire outside of the context I was able to capture. If you can figure out how to make this work, submit a pull request and I'll take a look.

**Comment by psamovich** [comment]
We use a server solution (reportportal.io) for reporting, it's client use onExecutionStart and onExecutionFinish events to mark the beginning and ending of execution. In case the client handles other lower levels events like onTestStart without handling onExecutionStart the server returns error as the parent item (the whole test launch) hasn't started. And this happens if I load the report portal client listener via ListenerChain. Now about why do I need the specific order of listener execution. I have a bunch of test listeners which output some files which must be attached to the test in report portal e.g. screenshot, har, etc. These listeners must be executed before the report portal client handles onTestFinish event, because in case the test gets marked as finished the attachments won't be attached.

**Comment by sbabcoc** [comment]
Fixed by https://github.com/Nordstrom/TestNG-Foundation/pull/28  
Note that this support must be activated via the **`ListenerChain`** service loader, as the `onExecutionStart` even fires before the **`@LinkedListeners`** annotations are processed.  
This support is available in release 1.11.0 - Let me know how this works for you.

**Comment by psamovich** [comment]
Works as expected when loading listeners via service loader. Thank you!
